<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoliceStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stations = [
            [
                'division_id' => 1,
                'station_name' => 'Pettah Police Station',
                'station_address' => 'Pettah, Colombo',
                'station_contact' => '071-8591555',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Keselwatta Police Station',
                'station_address' => 'Keselwatta, Colombo',
                'station_contact' => '071-8591556',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Dam Street Police Station',
                'station_address' => 'Dam Street, Colombo',
                'station_contact' => '071-8591557',
                'status' => 1, 
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Wolfendhal Street Police Station',
                'station_address' => 'Wolfendhal Street, Colombo',
                'station_contact' => '071-8591558',
                'status' => 1, 
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Fort Police Station',
                'station_address' => 'Fort, Colombo',
                'station_contact' => '071-8591560',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Slave Island Police Station',
                'station_address' => 'Slave Island, Colombo',
                'station_contact' => '071-8591561',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Maradana Police Station',
                'station_address' => 'Maradana, Colombo',
                'station_contact' => '071-8591563',
                'status' => 1, 
                'created_by' => 1,
            ],
            [
                'division_id' => 1,
                'station_name' => 'Maligawatta Police Station',
                'station_address' => 'Maligawatta, Colombo',
                'station_contact' => '071-8591564',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Colombo Harbour Police Station',
                'station_address' => 'Colombo Harbour, Colombo',
                'station_contact' => '071-8591567',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Fore Shore Police Station',
                'station_address' => 'Fore Shore, Colombo',
                'station_contact' => '071-8591568',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Modara Police Station',
                'station_address' => 'Modara, Colombo',
                'station_contact' => '071-8591570',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Kotahena Police Station',
                'station_address' => 'Kotahena, Colombo',
                'station_contact' => '071-8591571',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Mattakkuliya Police Station',
                'station_address' => 'Mattakkuliya, Colombo',
                'station_contact' => '071-8591572',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Bluemandal Police Station',
                'station_address' => 'Bluemandal, Colombo',
                'station_contact' => '071-8591573',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Grandpass Police Station',
                'station_address' => 'Grandpass, Colombo',
                'station_contact' => '071-8591575',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 2,
                'station_name' => 'Dematagoda Police Station',
                'station_address' => 'Dematagoda, Colombo',
                'station_contact' => '071-8591576',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Kollupitiya Police Station',
                'station_address' => 'Kollupitiya, Colombo',
                'station_contact' => '071-8591579',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Bambalapitiya Police Station',
                'station_address' => 'Bambalapitiya, Colombo',
                'station_contact' => '071-8591580',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Kirulapone Police Station',
                'station_address' => 'Kirulapone, Colombo',
                'station_contact' => '071-8591582',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Wellawatta Police Station',
                'station_address' => 'Wellawatta, Colombo',
                'station_contact' => '071-8591583',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Narahenpita Police Station',
                'station_address' => 'Narahenpita, Colombo',
                'station_contact' => '071-8591584',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'BMICH Police Station',
                'station_address' => 'BMICH, Colombo',
                'station_contact' => '071-8591586',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Borella Police Station',
                'station_address' => 'Borella, Colombo',
                'station_contact' => '071-8591587',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 3,
                'station_name' => 'Cinnamon Garden Police Station',
                'station_address' => 'Cinnamon Garden, Colombo',
                'station_contact' => '071-8591588',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Mirihana Police Station',
                'station_address' => 'Mirihana, Colombo',
                'station_contact' => '071-8591644',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Maharagama Police Station',
                'station_address' => 'Maharagama, Colombo',
                'station_contact' => '071-8591645',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Boralesgamuwa Police Station',
                'station_address' => 'Boralesgamuwa, Colombo',
                'station_contact' => '071-8591646',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Wellampitiya Police Station',
                'station_address' => 'Wellampitiya, Colombo',
                'station_contact' => '071-8591648',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Thalangama Police Station',
                'station_address' => 'Thalangama, Colombo',
                'station_contact' => '071-8591649',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Welikada Police Station',
                'station_address' => 'Welikada, Colombo',
                'station_contact' => '071-8591650',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Nawagamuwa Police Station',
                'station_address' => 'Nawagamuwa, Colombo',
                'station_contact' => '071-8591652',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Mulleriyawa Police Station',
                'station_address' => 'Mulleriyawa, Colombo',
                'station_contact' => '071-8591653',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Homagama Police Station',
                'station_address' => 'Homagama, Colombo',
                'station_contact' => '071-8591655',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Kottawa Police Station',
                'station_address' => 'Kottawa, Colombo',
                'station_contact' => '071-8591656',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Athurugiriya Police Station',
                'station_address' => 'Athurugiriya, Colombo',
                'station_contact' => '071-8591657',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Padukka Police Station',
                'station_address' => 'Padukka, Colombo',
                'station_contact' => '071-8591659',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Hanwella Police Station',
                'station_address' => 'Hanwella, Colombo',
                'station_contact' => '071-8591660',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Gothatuwa Police Station',
                'station_address' => 'Gothatuwa, Colombo',
                'station_contact' => '071-8592154',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 4,
                'station_name' => 'Meepe Police Station',
                'station_address' => 'Meepe, Colombo',
                'station_contact' => '071-8592179', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Mount Lavinia Police Station',
                'station_address' => 'Mount Lavinia, Colombo',
                'station_contact' => '071-8591664',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Piliyandala Police Station',
                'station_address' => 'Piliyandala, Colombo',
                'station_contact' => '071-8591665',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Angulana Police Station',
                'station_address' => 'Angulana, Colombo',
                'station_contact' => '071-8591666',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Dehiwala Police Station',
                'station_address' => 'Dehiwala, Colombo',
                'station_contact' => '071-8591668',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Kohuwala Police Station',
                'station_address' => 'Kohuwala, Colombo',
                'station_contact' => '071-8591669',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Moratuwa Police Station',
                'station_address' => 'Moratuwa, Colombo',
                'station_contact' => '071-8591671',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Kahathuduwa Police Station',
                'station_address' => 'Kahathuduwa, Colombo',
                'station_contact' => '071-8591672',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Moratumulla Police Station',
                'station_address' => 'Moratumulla, Colombo',
                'station_contact' => '071-8591673', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 5,
                'station_name' => 'Egoda Uyana Police Station',
                'station_address' => 'Egoda Uyana, Colombo',
                'station_contact' => '071-8592180',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Peliyagoda Police Station',
                'station_address' => 'Peliyagoda, Colombo',
                'station_contact' => '071-8591592',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Kelaniya Police Station',
                'station_address' => 'Kelaniya, Colombo',
                'station_contact' => '071-8591593',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Kandana Police Station',
                'station_address' => 'Kandana, Colombo',
                'station_contact' => '071-8591595',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Wattala Police Station',
                'station_address' => 'Wattala, Colombo',
                'station_contact' => '071-8591596',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Mahabage Police Station',
                'station_address' => 'Mahabage, Colombo',
                'station_contact' => '071-8591597',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Sapugaskanda Police Station',
                'station_address' => 'Sapugaskanda, Colombo',
                'station_contact' => '071-8591599',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Biyagama Police Station',
                'station_address' => 'Biyagama, Colombo',
                'station_contact' => '071-8591600',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Meegahawatta Police Station',
                'station_address' => 'Meegahawatta, Colombo',
                'station_contact' => '071-8591601',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Ja - Ela Police Station',
                'station_address' => 'Ja - Ela, Colombo',
                'station_contact' => '071-8591603',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Ragama Police Station',
                'station_address' => 'Ragama, Colombo',
                'station_contact' => '071-8591604',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Kiribathgoda Police Station',
                'station_address' => 'Kiribathgoda, Colombo',
                'station_contact' => '071-8591606',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 6,
                'station_name' => 'Kadawatha Police Station',
                'station_address' => 'Kadawatha, Colombo',
                'station_contact' => '071-8591607',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Gampaha Police Station',
                'station_address' => 'Gampaha, Colombo',
                'station_contact' => '071-8591611',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Minuwangoda Police Station',
                'station_address' => 'Minuwangoda, Colombo',
                'station_contact' => '071-8591612',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Kirindiwela Police Station',
                'station_address' => 'Kirindiwela, Colombo',
                'station_contact' => '071-8591614',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Dompe Police Station',
                'station_address' => 'Dompe, Colombo',
                'station_contact' => '071-8591615',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Pugoda Police Station',
                'station_address' => 'Pugoda, Colombo',
                'station_contact' => '071-8591616',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Ganemulla Police Station',
                'station_address' => 'Ganemulla, Colombo',
                'station_contact' => '071-8591618',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Weeragula Police Station',
                'station_address' => 'Weeragula, Colombo',
                'station_contact' => '071-8591619',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Weliweriya Police Station',
                'station_address' => 'Weliweriya, Colombo',
                'station_contact' => '071-8591620',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Malwathuhiripitiya Police Station',
                'station_address' => 'Malwathuhiripitiya, Colombo',
                'station_contact' => '071-8591621', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Nittambuwa Police Station',
                'station_address' => 'Nittambuwa, Colombo',
                'station_contact' => '071-8591623',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Weyangoda Police Station',
                'station_address' => 'Weyangoda, Colombo',
                'station_contact' => '071-8591624',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Meerigama Police Station',
                'station_address' => 'Meerigama, Colombo',
                'station_contact' => '071-8591625',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Pallewela Police Station',
                'station_address' => 'Pallewela, Colombo',
                'station_contact' => '071-8592152',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 7,
                'station_name' => 'Yakkala Police Station',
                'station_address' => 'Yakkala, Colombo',
                'station_contact' => '071-8592153', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Negombo Police Station',
                'station_address' => 'Negombo, Colombo',
                'station_contact' => '071-8591630',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Kochchikade Police Station',
                'station_address' => 'Kochchikade, Colombo',
                'station_contact' => '071-8591631',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Pamunugama Police Station',
                'station_address' => 'Pamunugama, Colombo',
                'station_contact' => '071-8591633',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Kotadeniyawa Police Station',
                'station_address' => 'Kotadeniyawa, Colombo',
                'station_contact' => '071-8591634',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Diulapitiya Police Station',
                'station_address' => 'Diulapitiya, Colombo',
                'station_contact' => '071-8591635',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Seeduwa Police Station',
                'station_address' => 'Seeduwa, Colombo',
                'station_contact' => '071-8591637',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Raddolugama Police Station',
                'station_address' => 'Raddolugama, Colombo',
                'station_contact' => '071-8591638', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Katunayaka Police Station',
                'station_address' => 'Katunayaka, Colombo',
                'station_contact' => '071-8591639',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Katana Police Station',
                'station_address' => 'Katana, Colombo',
                'station_contact' => '071-8591710',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 8,
                'station_name' => 'Dungalpitiya Police Station',
                'station_address' => 'Dungalpitiya, Colombo',
                'station_contact' => '071-8592186',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Panadura South Police Station',
                'station_address' => 'Panadura, Colombo',
                'station_contact' => '071-8591677',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Panadura North Police Station',
                'station_address' => 'Panadura, Colombo',
                'station_contact' => '071-8591678',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Wadduwa Police Station',
                'station_address' => 'Wadduwa, Colombo',
                'station_contact' => '071-8591679',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Bandaragama Police Station',
                'station_address' => 'Bandaragama, Colombo',
                'station_contact' => '071-8591681',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Anguruwatota Police Station',
                'station_address' => 'Anguruwatota, Colombo',
                'station_contact' => '071-8591682',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Millaniya Police Station',
                'station_address' => 'Millaniya, Colombo',
                'station_contact' => '071-8591683',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Horana Police Station',
                'station_address' => 'Horana, Colombo',
                'station_contact' => '071-8591685',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Ingiriya Police Station',
                'station_address' => 'Ingiriya, Colombo',
                'station_contact' => '071-8591686',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Moragahahena Police Station',
                'station_address' => 'Moragahahena, Colombo',
                'station_contact' => '071-8591687',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 9,
                'station_name' => 'Moronthuduwa Police Station',
                'station_address' => 'Moronthuduwa, Colombo',
                'station_contact' => '071-8592138', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Kalutara South Police Station',
                'station_address' => 'Kalutara, Colombo',
                'station_contact' => '071-8591691',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Kalutara North Police Station',
                'station_address' => 'Kalutara, Colombo',
                'station_contact' => '071-8591692',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Payagala Police Station',
                'station_address' => 'Payagala, Colombo',
                'station_contact' => '071-8591694',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Dodangoda Police Station',
                'station_address' => 'Dodangoda, Colombo',
                'station_contact' => '071-8591695', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Aluthgama Police Station',
                'station_address' => 'Aluthgama, Colombo',
                'station_contact' => '071-8591697',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Welipanna Police Station',
                'station_address' => 'Welipanna, Colombo',
                'station_contact' => '071-8591698', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Beruwala Police Station',
                'station_address' => 'Beruwala, Colombo',
                'station_contact' => '071-8591699',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Mathugama Police Station',
                'station_address' => 'Mathugama, Colombo',
                'station_contact' => '071-8591701',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Bulathsinhala Police Station',
                'station_address' => 'Bulathsinhala, Colombo',
                'station_contact' => '071-8591702',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Thebuwana Police Station',
                'station_address' => 'Thebuwana, Colombo',
                'station_contact' => '071-8591703',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Baduraliya Police Station',
                'station_address' => 'Baduraliya, Colombo',
                'station_contact' => '071-8591705',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Meegahathenna Police Station',
                'station_address' => 'Meegahathenna, Colombo',
                'station_contact' => '071-8591706', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Thiniyawala Police Station',
                'station_address' => 'Thiniyawala, Colombo',
                'station_contact' => '071-8591707', 
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'division_id' => 10,
                'station_name' => 'Mattegoda Police Station',
                'station_address' => 'Mattegoda, Colombo',
                'station_contact' => '071-8592207',
                'status' => 1,
                'created_by' => 1,
            ]
        ];

        DB::table('policestations')->insert($stations);
    }
}
